// ─── BidStream Auction dummy data ────────────────────────────────────────────
// 12 records covering all 4 statuses and all 6 categories.
// Imported by Auctions.jsx and any component that needs sample records.

const AUCTIONS = [
  {
    id: 1,
    title: 'Vintage Leica M6 Film Camera',
    category: 'Photography',
    seller: 'Ahmed Hassan',
    sellerAvatar: 'AH',
    currentBid: 1240,
    startingPrice: 800,
    bids: 18,
    status: 'live',
    timeLeft: '2h 14m',
    gradient: 'from-blue-600 via-blue-500 to-cyan-400',
    featured: true,
    description: 'Classic 35mm rangefinder camera in excellent condition.',
  },
  {
    id: 2,
    title: 'Air Jordan 1 Retro High OG Chicago',
    category: 'Fashion',
    seller: 'Sara Malik',
    sellerAvatar: 'SM',
    currentBid: 3800,
    startingPrice: 2500,
    bids: 47,
    status: 'ending_soon',
    timeLeft: '0h 38m',
    gradient: 'from-orange-500 via-amber-400 to-yellow-300',
    featured: true,
    description: 'Deadstock Chicago colourway, size US10, original box included.',
  },
  {
    id: 3,
    title: 'Rolex Submariner Date 2023',
    category: 'Luxury',
    seller: 'Omar Farooq',
    sellerAvatar: 'OF',
    currentBid: 12500,
    startingPrice: 10000,
    bids: 93,
    status: 'live',
    timeLeft: '4h 52m',
    gradient: 'from-primary-700 via-primary-600 to-secondary-600',
    featured: false,
    description: 'Full set with card and papers. Ref 126610LN.',
  },
  {
    id: 4,
    title: 'Gibson Les Paul Standard \'59',
    category: 'Music',
    seller: 'Bilal Chaudhry',
    sellerAvatar: 'BC',
    currentBid: 2150,
    startingPrice: 1500,
    bids: 31,
    status: 'sold',
    timeLeft: 'Ended',
    gradient: 'from-rose-600 via-pink-500 to-fuchsia-400',
    featured: false,
    description: 'Honey burst finish, all original hardware.',
  },
  {
    id: 5,
    title: 'Apple Mac Pro M2 Ultra 192GB',
    category: 'Technology',
    seller: 'Fatima Qureshi',
    sellerAvatar: 'FQ',
    currentBid: 6900,
    startingPrice: 5500,
    bids: 62,
    status: 'live',
    timeLeft: '8h 20m',
    gradient: 'from-slate-700 via-slate-600 to-gray-500',
    featured: false,
    description: 'Factory sealed, fully configured with 192GB unified memory.',
  },
  {
    id: 6,
    title: 'Original Banksy Flower Thrower Print',
    category: 'Art',
    seller: 'Zara Ahmed',
    sellerAvatar: 'ZA',
    currentBid: 8400,
    startingPrice: 5000,
    bids: 74,
    status: 'ending_soon',
    timeLeft: '0h 22m',
    gradient: 'from-emerald-600 via-teal-500 to-cyan-400',
    featured: true,
    description: 'Authenticated Pest Control certificate of authenticity included.',
  },
  {
    id: 7,
    title: 'Patek Philippe Nautilus Ref 5711',
    category: 'Luxury',
    seller: 'Hassan Raza',
    sellerAvatar: 'HR',
    currentBid: 48000,
    startingPrice: 40000,
    bids: 12,
    status: 'upcoming',
    timeLeft: 'Starts in 2d',
    gradient: 'from-amber-700 via-yellow-600 to-amber-400',
    featured: true,
    description: 'Blue dial, steel bracelet, full set 2022.',
  },
  {
    id: 8,
    title: 'Canon EOS R5 Mirrorless Body',
    category: 'Photography',
    seller: 'Nadia Shah',
    sellerAvatar: 'NS',
    currentBid: 2800,
    startingPrice: 2200,
    bids: 28,
    status: 'live',
    timeLeft: '5h 45m',
    gradient: 'from-red-600 via-red-500 to-rose-400',
    featured: false,
    description: '45MP full-frame, 8K RAW video, under 5000 actuations.',
  },
  {
    id: 9,
    title: 'Supreme Box Logo Hoodie FW22',
    category: 'Fashion',
    seller: 'Kamran Ali',
    sellerAvatar: 'KA',
    currentBid: 640,
    startingPrice: 400,
    bids: 55,
    status: 'ending_soon',
    timeLeft: '1h 03m',
    gradient: 'from-red-500 via-rose-500 to-pink-400',
    featured: false,
    description: 'Size Large, worn once, no stains or defects.',
  },
  {
    id: 10,
    title: 'Fender Custom Shop Stratocaster',
    category: 'Music',
    seller: 'Irfan Baig',
    sellerAvatar: 'IB',
    currentBid: 3200,
    startingPrice: 2800,
    bids: 19,
    status: 'upcoming',
    timeLeft: 'Starts in 1d',
    gradient: 'from-violet-600 via-purple-500 to-indigo-400',
    featured: false,
    description: 'Team Built masterbuilt, Olympic white, aged hardware.',
  },
  {
    id: 11,
    title: 'Jean-Michel Basquiat Lithograph',
    category: 'Art',
    seller: 'Amina Siddiqui',
    sellerAvatar: 'AS',
    currentBid: 4500,
    startingPrice: 3000,
    bids: 36,
    status: 'sold',
    timeLeft: 'Ended',
    gradient: 'from-yellow-500 via-orange-400 to-red-400',
    featured: false,
    description: 'Limited edition numbered lithograph, hand signed.',
  },
  {
    id: 12,
    title: 'Sony PlayStation 5 Digital Bundle',
    category: 'Technology',
    seller: 'Usman Tariq',
    sellerAvatar: 'UT',
    currentBid: 520,
    startingPrice: 450,
    bids: 41,
    status: 'live',
    timeLeft: '11h 10m',
    gradient: 'from-blue-700 via-indigo-600 to-violet-500',
    featured: false,
    description: 'Sealed bundle with two controllers and three games.',
  },
];

export const CATEGORIES = ['All', 'Photography', 'Fashion', 'Luxury', 'Music', 'Technology', 'Art'];

export const STATUSES = [
  { value: 'all',          label: 'All'          },
  { value: 'live',         label: 'Live'         },
  { value: 'ending_soon',  label: 'Ending Soon'  },
  { value: 'upcoming',     label: 'Upcoming'     },
  { value: 'sold',         label: 'Sold'         },
];

export const SORT_OPTIONS = [
  { value: 'newest',       label: 'Newest'       },
  { value: 'ending_soon',  label: 'Ending Soon'  },
  { value: 'highest_bid',  label: 'Highest Bid'  },
  { value: 'lowest_bid',   label: 'Lowest Bid'   },
  { value: 'most_popular', label: 'Most Popular' },
];

export default AUCTIONS;
